### PR TITLE
Update backend

### PR DESCRIPTION
**Pull request by oshotton**
- Added paid form field to the 'edit ticket' admin page.
- Fixed clear search button in admin tickets table.
- Improved code layout.

### CODE REVIEW

**Comment by addshore** [comment]
I'm not sure about the "Added paid form field to the 'edit ticket' admin page." as the whole point is that that is exactly what is returned by the payment provider.

Although I'm not even sure if we need that field at all any more....

**Comment by oshotton** [comment]
That's true but what if that we change their ticket and give them a partial refund? Or they pay via our handheld app and we manually assign them a ticket? 

I would keep the field as it shows how much money we have taken as supposed to just how many tickets were assigned. Especially useful for core/wave events where we don't want to give out more money than we took in!

**Comment by addshore** [comment]
> I would keep the field as it shows how much money we have taken as supposed to just how many tickets were assigned. Especially useful for core/wave events where we don't want to give out more money than we took in!

But I think it is more valuable to get that information from stripe now and not the website.

**Comment by addshore** [comment]
Same for this one @oshotton shall we just close it? :/

**Pull request closed without merging**
